source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.3'

inhibit_all_warnings!

target 'MobiusMobileWallet' do
  pod 'Fabric'
  pod 'Crashlytics'

  pod 'React', path: '../node_modules/react-native', subspecs: %W[
    Core
    CxxBridge
    DevSupport
    PrivateDatabase

    RCTActionSheet
    RCTAnimation
    RCTBlob
    RCTCameraRoll
    RCTImage
    RCTLinkingIOS
    RCTNetwork
    RCTSettings
    RCTText
    RCTWebSocket
    RCTVibration
  ]

  # Third-party dependencies required by React Native
  pod 'DoubleConversion', podspec: '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'Folly', podspec: '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'glog', podspec: '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'

  pod 'BVLinearGradient', path: '../node_modules/react-native-linear-gradient'
  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
  pod 'ReactNativeFabric', path: '../node_modules/react-native-fabric'
  pod 'RNDeviceInfo', path: '../node_modules/react-native-device-info'
  pod 'RNI18n', path: '../node_modules/react-native-i18n'
  pod 'RNKeychain', path: '../node_modules/react-native-keychain'
  pod 'RNSVG', path: '../node_modules/react-native-svg'
  pod 'RNVectorIcons', path: '../node_modules/react-native-vector-icons'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'
  pod 'react-native-randombytes', :path => '../node_modules/react-native-randombytes'
  pod 'react-native-splash-screen', path: '../node_modules/react-native-splash-screen'


  # Add new pods below this line

  target 'MobiusMobileWalletTests' do
    inherit! :search_paths
  end
end

